#!/usr/bin/env bash

#USAGE arg "<year>"
#USAGE arg "<day>"

set -euo pipefail

year=${usage_year?}
day=${usage_day?}
cookie=${AOC_COOKIE}
email=${AOC_EMAIL}

input_file="${year}/input/day${day}.txt"

mkdir -p "$(dirname "${input_file}")"

if [ -e "${input_file}" ]; then exit 0; fi

user_agent="github.com/ethansaxenian/advent-of-code/tree/main/${year} by ${email}"

curl \
  "https://adventofcode.com/${year}/day/${day}/input" \
  --cookie "session=${cookie}" \
  --header "User-Agent: ${user_agent}" \
  --silent > "${input_file}"


