#!/usr/bin/env bash

#USAGE arg "<year>"
#USAGE arg "<day>"
#USAGE flag "-l --language <language>" {
#USAGE   choices "python" "py" "typescript" "ts"
#USAGE   default "python"
#USAGE }

year=${usage_year?}
day=${usage_day?}
language=${usage_language:-python}


function init_python {
  file="${year}/${day}.py"
  if [[ -e $file ]]; then
    echo "Day ${day} already exists"
    exit 0
  fi

  echo "import util


def part1(input: str) -> int:
    for line in input.splitlines():
        pass


def part2(input: str) -> int:
    for line in input.splitlines():
        pass


if __name__ == \"__main__\":
    util.run(${day}, ${year}, part1, part2)" > "$file"
}

function init_typescript {
  file="${year}/${day}.ts"
  if [[ -e $file ]]; then
    echo "Day ${day} already exists"
    exit 0
  fi

  echo "import { run } from \"./util\";

async function part1(input: string): Promise<number> {
  return 0
}

async function part2(input: string): Promise<number> {
  return 0
}

run(${day}, ${year}, part1, part2);" > "$file"
}

case "$language" in
  "python" | "py")
    init_python ;;
  "typescript" | "ts")
    init_typescript ;;
esac
