#!/usr/bin/env bash

#USAGE arg "<day>"
#USAGE flag "-l --language <language>" {
#USAGE   choices "python" "py" "typescript" "ts"
#USAGE   default "python"
#USAGE }

#MISE dir="{{cwd}}"

day=${usage_day?}
language=${usage_language:-python}


function init_python {
  if [[ -e "${day}.py" ]]; then
    echo "Day ${day} already exists"
    exit 0
  fi

  echo "import util


def part1(input: str) -> int:
    for line in input.splitlines():
        pass


def part2(input: str) -> int:
    for line in input.splitlines():
        pass


if __name__ == \"__main__\":
    util.run(${day}, part1, part2)" > "${day}.py"
}

function init_typescript {
  if [[ -e "${day}.ts" ]]; then
    echo "Day ${day} already exists"
    exit 0
  fi

  echo "import { run } from \"./util\";

async function part1(input: string): Promise<number> {
  return 0
}

async function part2(input: string): Promise<number> {
  return 0
}

run(${day}, part1, part2);" > "${day}.ts"
}

case "$language" in
  "python" | "py")
    init_python ;;
  "typescript" | "ts")
    init_typescript ;;
esac
